import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { curriculum } from './src/data/curriculum';
import { Difficulty, Grade, Question, TestHistory, WrongRecord } from './src/types';
import { generateQuestions } from './src/services/questionEngine';
import { addHistory, addWrong, clearWrongs, getHistory, getWrongs, removeWrong } from './src/services/storage';

const C={pink:'#D94A86',deep:'#A92F67',soft:'#FBEAF2',soft2:'#FFF5F9',border:'#F4CADC',ink:'#382731',muted:'#7B6872',green:'#238A64',greenSoft:'#E8F7F1',red:'#C84763',redSoft:'#FDECEF',white:'#FFFFFF',gold:'#C78930'};
const grades:Grade[]=[9,10,11,12];
const counts=[5,10,15,20,30];
const difficulties:Difficulty[]=['Kolay','Orta','Zor','Karma'];
type Screen='home'|'setup'|'loading'|'quiz'|'result'|'review'|'wrongs'|'history';

type AnswerRecord={selected:number; correct:boolean};

export default function App(){
  const [screen,setScreen]=useState<Screen>('home');
  const [grade,setGrade]=useState<Grade>(9); const [topic,setTopic]=useState('Tüm Konular'); const [count,setCount]=useState(10); const [difficulty,setDifficulty]=useState<Difficulty>('Karma');
  const [questions,setQuestions]=useState<Question[]>([]); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<AnswerRecord[]>([]); const [selected,setSelected]=useState<number|null>(null); const [locked,setLocked]=useState(false); const [progress,setProgress]=useState(0);
  const [wrongs,setWrongs]=useState<WrongRecord[]>([]); const [history,setHistory]=useState<TestHistory[]>([]); const [practiceWrong,setPracticeWrong]=useState(false);
  const {width}=useWindowDimensions(); const tablet=width>=700; const contentWidth=Math.min(width-(tablet?64:24),1040);
  const current=questions[index]; const score=useMemo(()=>answers.filter(a=>a.correct).length,[answers]);

  const refresh=async()=>{setWrongs(await getWrongs());setHistory(await getHistory())};
  useEffect(()=>{refresh()},[]);
  const goHome=()=>{setScreen('home');setSelected(null);setLocked(false);setPracticeWrong(false);refresh()};
  const chooseGrade=(g:Grade)=>{setGrade(g);setTopic('Tüm Konular');setScreen('setup')};

  const start=async()=>{
    setProgress(0);setScreen('loading');setPracticeWrong(false);
    try{const qs=await generateQuestions({grade,topic,count,difficulty},(d,t)=>setProgress(Math.round(d/t*100)));setQuestions(qs);setAnswers([]);setIndex(0);setSelected(null);setLocked(false);setScreen('quiz')}
    catch{Alert.alert('Test hazırlanamadı','Beklenmeyen bir hata oluştu. Mevcut test silinmeden tekrar deneyebilirsin.');setScreen('setup')}
  };
  const startWrongPractice=()=>{
    if(!wrongs.length)return; const qs=[...wrongs].sort((a,b)=>b.lastWrongAt-a.lastWrongAt).slice(0,Math.min(20,wrongs.length));
    setQuestions(qs);setAnswers([]);setIndex(0);setSelected(null);setLocked(false);setPracticeWrong(true);setScreen('quiz');
  };
  const answer=async(option:number)=>{
    if(locked)return;setSelected(option);setLocked(true);const correct=option===current.correctIndex;setAnswers(a=>[...a,{selected:option,correct}]);
    if(!correct){await addWrong(current);refresh()} else if(practiceWrong){await removeWrong(current.id);refresh()}
  };
  const next=async()=>{
    setSelected(null);setLocked(false);
    if(index+1<questions.length){setIndex(i=>i+1);return}
    if(!practiceWrong){await addHistory({id:`h-${Date.now()}`,grade,topic,difficulty,count:questions.length,correct:score,date:Date.now()});await refresh()}
    setScreen('result');
  };
  const clearWrongList=()=>Alert.alert('Yanlışları temizle','Kaydedilen tüm yanlış sorular silinsin mi?',[{text:'Vazgeç',style:'cancel'},{text:'Temizle',style:'destructive',onPress:async()=>{await clearWrongs();await refresh()}}]);

  return <SafeAreaProvider><StatusBar style="dark"/><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={[s.scroll,{paddingHorizontal:tablet?32:12}]} keyboardShouldPersistTaps="handled"><View style={[s.shell,{width:contentWidth}]}> 
    <Header screen={screen} goHome={goHome}/>
    {screen==='home'&&<Home tablet={tablet} history={history} wrongs={wrongs} chooseGrade={chooseGrade} onWrongs={()=>setScreen('wrongs')} onHistory={()=>setScreen('history')}/>} 
    {screen==='setup'&&<Setup grade={grade} topic={topic} setTopic={setTopic} count={count} setCount={setCount} difficulty={difficulty} setDifficulty={setDifficulty} start={start}/>} 
    {screen==='loading'&&<Loading progress={progress}/>} 
    {screen==='quiz'&&current&&<Quiz q={current} index={index} total={questions.length} selected={selected} locked={locked} onAnswer={answer} onNext={next}/>} 
    {screen==='result'&&<Result score={score} total={questions.length} practice={practiceWrong} onReview={()=>setScreen('review')} onAgain={()=>practiceWrong?startWrongPractice():setScreen('setup')} goHome={goHome}/>} 
    {screen==='review'&&<Review questions={questions} answers={answers} goBack={()=>setScreen('result')}/>} 
    {screen==='wrongs'&&<Wrongs data={wrongs} start={startWrongPractice} clear={clearWrongList}/>} 
    {screen==='history'&&<History data={history}/>} 
  </View></ScrollView></SafeAreaView></SafeAreaProvider>;
}

function Header({screen,goHome}:{screen:Screen;goHome:()=>void}){return <View style={s.header}><View><Text style={s.brand}>Kimya Pembe</Text><Text style={s.sub}>Lise Kimya Çalışma Asistanı</Text></View>{screen!=='home'&&<Pressable onPress={goHome} style={s.homeBtn}><Text style={s.homeBtnText}>⌂ Ana Sayfa</Text></Pressable>}</View>}
function Home({tablet,history,wrongs,chooseGrade,onWrongs,onHistory}:{tablet:boolean;history:TestHistory[];wrongs:WrongRecord[];chooseGrade:(g:Grade)=>void;onWrongs:()=>void;onHistory:()=>void}){
 const solved=history.reduce((a,h)=>a+h.count,0),correct=history.reduce((a,h)=>a+h.correct,0),rate=solved?Math.round(correct/solved*100):0;
 return <><View style={s.hero}><Text style={s.heroEmoji}>⚗️🌸</Text><Text style={s.heroTitle}>Kimyayı adım adım güçlendir.</Text><Text style={s.heroText}>Sınıfını seç, konu ve zorluk düzeyini belirle. Testin hazırlanırken tamamlanan sorular korunur.</Text></View>
 <View style={s.statsRow}><MiniStat n={`${solved}`} t="Çözülen"/><MiniStat n={`%${rate}`} t="Başarı"/><MiniStat n={`${wrongs.length}`} t="Yanlışlarda"/></View>
 <View style={[s.grid,tablet&&s.gridTablet]}>{grades.map(g=><Pressable key={g} onPress={()=>chooseGrade(g)} style={[s.gradeCard,tablet&&s.gradeCardTablet]}><View style={s.gradeBubble}><Text style={s.gradeNo}>{g}</Text></View><Text style={s.gradeTitle}>Sınıf Kimya</Text><Text style={s.badge}>{curriculum[g].badge}</Text><Text style={s.arrow}>›</Text></Pressable>)}</View>
 <View style={[s.quickRow,tablet&&{flexDirection:'row'}]}><Pressable onPress={onWrongs} style={[s.quickCard,tablet&&{flex:1}]}><Text style={s.quickIcon}>♡</Text><View><Text style={s.quickTitle}>Yanlışlarım</Text><Text style={s.quickText}>{wrongs.length?`${wrongs.length} soru tekrar bekliyor`:'Henüz kayıtlı yanlış yok'}</Text></View></Pressable><Pressable onPress={onHistory} style={[s.quickCard,tablet&&{flex:1}]}><Text style={s.quickIcon}>↗</Text><View><Text style={s.quickTitle}>Çalışma Geçmişi</Text><Text style={s.quickText}>{history.length?`Son ${history.length} test kayıtlı`:'İlk testini oluştur'}</Text></View></Pressable></View>
 <Text style={s.footerNote}>Sorular MEB öğretim programı ve lise ders kitabı kapsamına göre hazırlanır. 9 ve 10. sınıf menüleri yeni müfredata göre düzenlenmiştir.</Text></>}
function MiniStat({n,t}:{n:string;t:string}){return <View style={s.miniStat}><Text style={s.miniN}>{n}</Text><Text style={s.miniT}>{t}</Text></View>}
function Setup({grade,topic,setTopic,count,setCount,difficulty,setDifficulty,start}:{grade:Grade;topic:string;setTopic:(v:string)=>void;count:number;setCount:(v:number)=>void;difficulty:Difficulty;setDifficulty:(v:Difficulty)=>void;start:()=>void}){return <><View style={s.pageHead}><Text style={s.kicker}>{curriculum[grade].badge}</Text><Text style={s.pageTitle}>{curriculum[grade].title}</Text><Text style={s.pageDesc}>Test ayarlarını seç. Sorular seçtiğin sınıf ve konu düzeyinde kalır.</Text></View><Section title="Konu"><View style={s.chips}>{curriculum[grade].topics.map(t=><Chip key={t} text={t} active={topic===t} onPress={()=>setTopic(t)}/>)}</View></Section><Section title="Soru sayısı"><View style={s.chips}>{counts.map(c=><Chip key={c} text={`${c} soru`} active={count===c} onPress={()=>setCount(c)}/>)}</View></Section><Section title="Zorluk"><View style={s.chips}>{difficulties.map(d=><Chip key={d} text={d} active={difficulty===d} onPress={()=>setDifficulty(d)}/>)}</View></Section><View style={s.infoBox}><Text style={s.infoTitle}>✓ Güvenli üretim modu</Text><Text style={s.infoText}>Sorular en fazla 5’li paketlerle hazırlanır. Çevrim içi üretim kullanılırsa hata veren paket yeniden denenir; başarılı sorular silinmez. Sunucu kullanılamazsa uygulama yerel MEB-kapsamlı soru motoruyla testi tamamlar.</Text></View><Pressable onPress={start} style={s.primary}><Text style={s.primaryText}>{count} Soruluk Testi Başlat</Text></Pressable></>}
function Loading({progress}:{progress:number}){return <View style={s.center}><View style={s.loaderBubble}><ActivityIndicator size="large" color={C.pink}/></View><Text style={s.loadingTitle}>Test hazırlanıyor…</Text><Text style={s.progress}>%{progress}</Text><View style={s.progressOuter}><View style={[s.progressInner,{width:`${progress}%`}]} /></View><Text style={s.pageDesc}>Hazırlanan sorular korunuyor. Bir bölüm hata verirse yalnızca eksik bölüm tamamlanıyor.</Text></View>}
function Quiz({q,index,total,selected,locked,onAnswer,onNext}:{q:Question;index:number;total:number;selected:number|null;locked:boolean;onAnswer:(i:number)=>void;onNext:()=>void}){const ok=selected===q.correctIndex;return <><View style={s.quizTop}><Text style={s.counter}>Soru {index+1} / {total}</Text><Text style={s.badge}>{q.difficulty}</Text></View><View style={s.bar}><View style={[s.barFill,{width:`${((index+1)/total)*100}%`}]} /></View><View style={s.questionCard}><Text style={s.topicLabel}>{q.topic}</Text><Text style={s.stem}>{q.stem}</Text>{q.options.map((o,i)=>{const isSel=selected===i,isCorrect=locked&&i===q.correctIndex,isWrong=locked&&isSel&&!isCorrect;return <Pressable disabled={locked} key={i} onPress={()=>onAnswer(i)} style={[s.option,isCorrect&&s.optionCorrect,isWrong&&s.optionWrong]}><Text style={[s.optionLetter,isCorrect&&s.letterCorrect,isWrong&&s.letterWrong]}>{String.fromCharCode(65+i)}</Text><Text style={s.optionText}>{o}</Text></Pressable>})}{locked&&<View style={[s.feedback,ok?s.feedbackOk:s.feedbackBad]}><Text style={[s.feedbackTitle,{color:ok?C.green:C.red}]}>{ok?'✓ Doğru':'✕ Yanlış'}</Text><Text style={s.feedbackText}>{q.explanation}</Text><Text style={s.source}>{q.sourceNote}</Text></View>}{locked&&<Pressable style={s.primary} onPress={onNext}><Text style={s.primaryText}>{index+1===total?'Testi Bitir':'Sonraki Soru →'}</Text></Pressable>}</View></>}
function Result({score,total,practice,onReview,onAgain,goHome}:{score:number;total:number;practice:boolean;onReview:()=>void;onAgain:()=>void;goHome:()=>void}){const rate=total?Math.round(score/total*100):0;return <View style={s.center}><Text style={s.heroEmoji}>{rate>=80?'🌸✨':rate>=50?'🌷':'🧪'}</Text><Text style={s.pageTitle}>{practice?'Tekrar tamamlandı':'Test tamamlandı'}</Text><Text style={s.score}>{score}<Text style={s.scoreSmall}> / {total}</Text></Text><Text style={s.rate}>%{rate} başarı</Text><Text style={s.pageDesc}>{rate>=80?'Çok iyi gidiyor. Zorluğu artırabilirsin.':rate>=50?'Temel iyi; yanlışları inceleyerek güçlendirebilirsin.':'Yanlışları inceleyip aynı konuyu tekrar çözmek faydalı olur.'}</Text><Pressable style={s.primary} onPress={onReview}><Text style={s.primaryText}>Soruları ve Çözümleri İncele</Text></Pressable><Pressable style={s.secondary} onPress={onAgain}><Text style={s.secondaryText}>{practice?'Yanlışlardan Tekrar Çöz':'Yeni Test Oluştur'}</Text></Pressable><Pressable style={s.textBtn} onPress={goHome}><Text style={s.textBtnText}>Ana Sayfaya Dön</Text></Pressable></View>}
function Review({questions,answers,goBack}:{questions:Question[];answers:AnswerRecord[];goBack:()=>void}){return <><Text style={s.pageTitle}>Test İncelemesi</Text><Text style={s.pageDesc}>Her sorunun doğru cevabı ve kısa çözümü.</Text>{questions.map((q,i)=>{const a=answers[i];return <View key={`${q.id}-${i}`} style={s.reviewCard}><Text style={s.reviewNo}>Soru {i+1} • {a?.correct?'Doğru':'Yanlış'}</Text><Text style={s.reviewStem}>{q.stem}</Text><Text style={s.correctText}>Doğru: {String.fromCharCode(65+q.correctIndex)}) {q.options[q.correctIndex]}</Text>{a&&!a.correct&&<Text style={s.wrongText}>Senin cevabın: {String.fromCharCode(65+a.selected)}) {q.options[a.selected]}</Text>}<Text style={s.explain}>{q.explanation}</Text><Text style={s.source}>{q.sourceNote}</Text></View>})}<Pressable style={s.secondary} onPress={goBack}><Text style={s.secondaryText}>Sonuç Ekranına Dön</Text></Pressable></>}
function Wrongs({data,start,clear}:{data:WrongRecord[];start:()=>void;clear:()=>void}){return <><View style={s.pageHead}><Text style={s.pageTitle}>Yanlışlarım</Text><Text style={s.pageDesc}>Yanlış cevapladığın sorular burada birikir. Tekrar modunda doğru yaptıkların listeden çıkarılır.</Text></View>{!data.length?<Empty icon="♡" text="Henüz kayıtlı yanlış yok. Test çözdükçe yanlışların burada görünecek."/>:<><View style={s.wrongActionRow}><Pressable style={[s.primary,{flex:1,marginTop:0}]} onPress={start}><Text style={s.primaryText}>Yanlışlardan Test Oluştur</Text></Pressable><Pressable style={s.clearBtn} onPress={clear}><Text style={s.clearText}>Temizle</Text></Pressable></View>{data.slice(0,50).map((q,i)=><View key={`${q.id}-${i}`} style={s.smallCard}><Text style={s.topicLabel}>{q.grade}. Sınıf • {q.topic}</Text><Text style={s.smallStem}>{q.stem}</Text><Text style={s.muted}>Yanlış sayısı: {q.wrongCount}</Text></View>)}</>}</>}
function History({data}:{data:TestHistory[]}){return <><View style={s.pageHead}><Text style={s.pageTitle}>Çalışma Geçmişi</Text><Text style={s.pageDesc}>Son testlerin ve başarı oranların cihazında saklanır.</Text></View>{!data.length?<Empty icon="↗" text="Henüz tamamlanan test yok."/>:data.map(h=><View key={h.id} style={s.historyCard}><View><Text style={s.historyTitle}>{h.grade}. Sınıf • {h.topic}</Text><Text style={s.muted}>{new Date(h.date).toLocaleDateString('tr-TR')} • {h.difficulty} • {h.count} soru</Text></View><Text style={s.historyScore}>%{Math.round(h.correct/h.count*100)}</Text></View>)}</>}
function Empty({icon,text}:{icon:string;text:string}){return <View style={s.empty}><Text style={s.emptyIcon}>{icon}</Text><Text style={s.pageDesc}>{text}</Text></View>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Chip({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&s.chipTextActive]}>{text}</Text></Pressable>}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.soft2},scroll:{alignItems:'center',paddingBottom:50},shell:{maxWidth:1040},header:{minHeight:78,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{fontSize:24,fontWeight:'900',color:C.ink,letterSpacing:-.4},sub:{fontSize:12,color:C.muted,marginTop:2},homeBtn:{paddingHorizontal:13,paddingVertical:9,backgroundColor:C.soft,borderRadius:18},homeBtnText:{color:C.deep,fontWeight:'800'},
 hero:{backgroundColor:C.white,borderRadius:30,padding:24,marginBottom:14,borderWidth:1,borderColor:C.border},heroEmoji:{fontSize:39,marginBottom:8},heroTitle:{fontSize:29,fontWeight:'900',color:C.ink,lineHeight:35,letterSpacing:-.7},heroText:{fontSize:15,color:C.muted,marginTop:8,lineHeight:22},statsRow:{flexDirection:'row',gap:8,marginBottom:14},miniStat:{flex:1,backgroundColor:C.soft,borderRadius:18,padding:12,alignItems:'center'},miniN:{fontSize:20,fontWeight:'900',color:C.deep},miniT:{fontSize:11,color:C.muted,fontWeight:'700',marginTop:2},
 grid:{gap:11},gridTablet:{flexDirection:'row',flexWrap:'wrap'},gradeCard:{backgroundColor:C.white,borderRadius:25,padding:19,borderWidth:1,borderColor:C.border,minHeight:135,justifyContent:'center'},gradeCardTablet:{width:'49%'},gradeBubble:{width:54,height:54,borderRadius:18,backgroundColor:C.soft,alignItems:'center',justifyContent:'center',marginBottom:8},gradeNo:{fontSize:27,fontWeight:'900',color:C.deep},gradeTitle:{fontSize:17,fontWeight:'900',color:C.ink},badge:{alignSelf:'flex-start',marginTop:7,backgroundColor:C.soft,color:C.deep,paddingHorizontal:10,paddingVertical:5,borderRadius:12,fontSize:11,fontWeight:'800'},arrow:{position:'absolute',right:18,top:47,fontSize:38,color:'#EDA6C4'},
 quickRow:{gap:10,marginTop:14},quickCard:{backgroundColor:C.white,borderRadius:22,padding:16,borderWidth:1,borderColor:C.border,flexDirection:'row',alignItems:'center',gap:12},quickIcon:{width:42,height:42,textAlign:'center',textAlignVertical:'center',fontSize:25,color:C.deep,backgroundColor:C.soft,borderRadius:14},quickTitle:{fontWeight:'900',fontSize:15,color:C.ink},quickText:{fontSize:12,color:C.muted,marginTop:3},footerNote:{fontSize:11,color:C.muted,lineHeight:17,textAlign:'center',marginTop:18,paddingHorizontal:10},
 pageHead:{marginTop:10},kicker:{color:C.deep,fontWeight:'900',fontSize:12,textTransform:'uppercase',letterSpacing:.6},pageTitle:{fontSize:29,fontWeight:'900',color:C.ink,marginTop:5,letterSpacing:-.6},pageDesc:{fontSize:15,color:C.muted,marginTop:6,lineHeight:22,textAlign:'center'},section:{marginTop:24},sectionTitle:{fontSize:16,fontWeight:'900',color:C.ink,marginBottom:10},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingVertical:11,paddingHorizontal:14,borderRadius:17,backgroundColor:C.white,borderWidth:1,borderColor:C.border},chipActive:{backgroundColor:C.pink,borderColor:C.pink},chipText:{color:C.ink,fontWeight:'700',fontSize:13},chipTextActive:{color:C.white},
 infoBox:{marginTop:25,backgroundColor:C.soft,borderRadius:20,padding:15,borderWidth:1,borderColor:C.border},infoTitle:{color:C.deep,fontWeight:'900',fontSize:14},infoText:{color:C.muted,fontSize:12,lineHeight:18,marginTop:5},primary:{backgroundColor:C.pink,borderRadius:19,paddingVertical:15,paddingHorizontal:20,alignItems:'center',marginTop:24},primaryText:{color:C.white,fontSize:15,fontWeight:'900'},secondary:{borderWidth:1,borderColor:C.pink,borderRadius:19,paddingVertical:14,paddingHorizontal:20,alignItems:'center',marginTop:10},secondaryText:{color:C.deep,fontWeight:'900'},textBtn:{padding:14,marginTop:4},textBtnText:{color:C.muted,fontWeight:'800'},
 center:{alignItems:'center',justifyContent:'center',paddingVertical:60},loaderBubble:{width:80,height:80,borderRadius:28,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},loadingTitle:{fontSize:21,fontWeight:'900',color:C.ink,marginTop:18},progress:{fontSize:38,fontWeight:'900',color:C.deep,marginVertical:8},progressOuter:{height:9,width:'85%',backgroundColor:C.soft,borderRadius:99,overflow:'hidden',marginBottom:7},progressInner:{height:'100%',backgroundColor:C.pink,borderRadius:99},
 quizTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10},counter:{fontWeight:'900',color:C.ink,fontSize:16},bar:{height:8,backgroundColor:C.soft,borderRadius:99,overflow:'hidden',marginTop:13},barFill:{height:'100%',backgroundColor:C.pink,borderRadius:99},questionCard:{backgroundColor:C.white,borderRadius:27,padding:19,marginTop:16,borderWidth:1,borderColor:C.border},topicLabel:{color:C.deep,fontWeight:'800',fontSize:11,lineHeight:16},stem:{fontSize:20,fontWeight:'800',color:C.ink,lineHeight:29,marginVertical:17},option:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#EDD7E1',borderRadius:17,padding:13,marginBottom:9,backgroundColor:C.white},optionCorrect:{borderColor:'#8FD4BC',backgroundColor:C.greenSoft},optionWrong:{borderColor:'#F0A5B5',backgroundColor:C.redSoft},optionLetter:{width:34,height:34,borderRadius:17,textAlign:'center',textAlignVertical:'center',backgroundColor:C.soft,color:C.deep,fontWeight:'900',marginRight:11},letterCorrect:{backgroundColor:C.green,color:C.white},letterWrong:{backgroundColor:C.red,color:C.white},optionText:{flex:1,color:C.ink,fontSize:15,lineHeight:21,fontWeight:'600'},feedback:{borderRadius:18,padding:14,marginTop:7},feedbackOk:{backgroundColor:C.greenSoft},feedbackBad:{backgroundColor:C.redSoft},feedbackTitle:{fontSize:15,fontWeight:'900'},feedbackText:{color:C.ink,fontSize:13,lineHeight:19,marginTop:5},source:{fontSize:10,color:C.muted,lineHeight:15,marginTop:8,fontStyle:'italic'},
 score:{fontSize:58,fontWeight:'900',color:C.deep,marginTop:12},scoreSmall:{fontSize:26,color:C.muted},rate:{fontSize:17,fontWeight:'900',color:C.pink,marginBottom:4},reviewCard:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:20,padding:16,marginTop:12},reviewNo:{color:C.deep,fontSize:12,fontWeight:'900'},reviewStem:{color:C.ink,fontWeight:'800',fontSize:16,lineHeight:23,marginVertical:9},correctText:{color:C.green,fontWeight:'800',fontSize:13,lineHeight:19},wrongText:{color:C.red,fontWeight:'800',fontSize:13,lineHeight:19,marginTop:3},explain:{color:C.ink,fontSize:13,lineHeight:19,marginTop:9},
 wrongActionRow:{flexDirection:'row',gap:8,alignItems:'center',marginTop:20},clearBtn:{paddingVertical:15,paddingHorizontal:16,borderRadius:18,backgroundColor:C.redSoft},clearText:{fontWeight:'900',color:C.red},smallCard:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:19,padding:15,marginTop:10},smallStem:{fontSize:14,fontWeight:'800',lineHeight:20,color:C.ink,marginVertical:7},muted:{fontSize:11,color:C.muted,lineHeight:16},empty:{alignItems:'center',paddingVertical:65,paddingHorizontal:20},emptyIcon:{fontSize:52,color:C.pink},historyCard:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:19,padding:15,marginTop:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},historyTitle:{fontSize:14,fontWeight:'900',color:C.ink,maxWidth:270},historyScore:{fontSize:22,fontWeight:'900',color:C.deep}
});
